import { useState } from "react"
import { NavLink, Outlet, useLocation } from "react-router-dom"
import * as DialogPrimitive from "@radix-ui/react-dialog"
import { motion } from "motion/react"
import { cn } from "@/lib/utils"
import {
  LayoutDashboard,
  Users,
  UploadCloud,
  Settings2,
  Radio,
  Menu,
} from "lucide-react"

const navItems = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard, end: true },
  { to: "/leads", label: "Pipeline", icon: Users },
  { to: "/data", label: "Data Sources", icon: UploadCloud },
  { to: "/setup", label: "Persona & Solution", icon: Settings2 },
]

function BrandMark({ compact = false }: { compact?: boolean }) {
  return (
    <div className="flex items-center gap-2">
      <div
        className={cn(
          "flex items-center justify-center rounded-lg bg-primary text-primary-foreground",
          compact ? "h-7 w-7" : "h-8 w-8"
        )}
      >
        <Radio className={compact ? "h-3.5 w-3.5" : "h-4 w-4"} />
      </div>
      <div>
        <p className="font-heading text-sm font-bold leading-none">Signalis</p>
        {!compact && (
          <p className="text-[11px] text-muted-foreground mt-0.5">Buying Signal Copilot</p>
        )}
      </div>
    </div>
  )
}

function NavLinks({ onNavigate, indicatorId }: { onNavigate?: () => void; indicatorId: string }) {
  const location = useLocation()

  return (
    <nav className="flex flex-col gap-1 px-3 py-2">
      {navItems.map((item) => {
        const isActive = item.end
          ? location.pathname === item.to
          : location.pathname === item.to || location.pathname.startsWith(`${item.to}/`)

        return (
          <NavLink
            key={item.to}
            to={item.to}
            end={item.end}
            onClick={onNavigate}
            className={cn(
              "relative flex items-center gap-2.5 rounded-md px-3 py-2 text-sm font-medium transition-colors",
              isActive
                ? "bg-secondary text-foreground"
                : "text-muted-foreground hover:bg-secondary/60 hover:text-foreground"
            )}
          >
            {isActive && (
              <motion.span
                layoutId={indicatorId}
                className="absolute left-0 top-1.5 bottom-1.5 w-0.5 rounded-full bg-accent"
                transition={{ type: "spring", stiffness: 500, damping: 40 }}
              />
            )}
            <item.icon className="h-4 w-4" />
            {item.label}
          </NavLink>
        )
      })}
    </nav>
  )
}

export function AppShell() {
  const [mobileNavOpen, setMobileNavOpen] = useState(false)

  return (
    <div className="min-h-screen flex app-ambient-bg">
      <aside className="hidden md:flex w-60 shrink-0 flex-col border-r border-border bg-surface">
        <div className="px-5 py-5">
          <BrandMark />
        </div>
        <NavLinks indicatorId="nav-indicator-desktop" />
        <div className="mt-auto px-5 py-4 border-t border-border">
          <p className="text-[11px] text-muted-foreground leading-snug">
            Every stage classification and outreach plan is generated by a
            traceable multi-agent pipeline. Nothing ships to a lead without
            explicit approval.
          </p>
        </div>
      </aside>
      <div className="flex-1 min-w-0 flex flex-col">
        <header className="md:hidden flex items-center justify-between gap-2 border-b border-border px-4 py-3 bg-surface">
          <BrandMark compact />
          <DialogPrimitive.Root open={mobileNavOpen} onOpenChange={setMobileNavOpen}>
            <DialogPrimitive.Trigger asChild>
              <button
                type="button"
                aria-label="Open navigation menu"
                className="flex h-9 w-9 items-center justify-center rounded-md text-muted-foreground hover:bg-secondary hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              >
                <Menu className="h-5 w-5" />
              </button>
            </DialogPrimitive.Trigger>
            <DialogPrimitive.Portal>
              <DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-background/70 backdrop-blur-sm data-[state=open]:animate-fade-in" />
              <DialogPrimitive.Content
                className="fixed inset-y-0 left-0 z-50 flex w-72 max-w-[80vw] flex-col border-r border-border bg-surface shadow-raised data-[state=open]:animate-slide-in-left motion-reduce:data-[state=open]:animate-none"
                aria-describedby={undefined}
              >
                <DialogPrimitive.Title className="sr-only">Navigation</DialogPrimitive.Title>
                <div className="px-5 py-5">
                  <BrandMark />
                </div>
                <NavLinks onNavigate={() => setMobileNavOpen(false)} indicatorId="nav-indicator-mobile" />
              </DialogPrimitive.Content>
            </DialogPrimitive.Portal>
          </DialogPrimitive.Root>
        </header>
        <main className="flex-1 min-w-0 p-4 md:p-8 max-w-[1400px] w-full mx-auto">
          <Outlet />
        </main>
      </div>
    </div>
  )
}
