import { NavLink, Outlet } from "react-router-dom"
import { cn } from "@/lib/utils"
import {
  LayoutDashboard,
  Users,
  UploadCloud,
  Settings2,
  Radio,
} from "lucide-react"

const navItems = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard, end: true },
  { to: "/leads", label: "Pipeline", icon: Users },
  { to: "/data", label: "Data Sources", icon: UploadCloud },
  { to: "/setup", label: "Persona & Solution", icon: Settings2 },
]

export function AppShell() {
  return (
    <div className="min-h-screen flex bg-background">
      <aside className="hidden md:flex w-60 shrink-0 flex-col border-r border-border bg-surface">
        <div className="flex items-center gap-2 px-5 py-5">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
            <Radio className="h-4 w-4" />
          </div>
          <div>
            <p className="font-heading text-sm font-bold leading-none">Signalis</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Buying Signal Copilot</p>
          </div>
        </div>
        <nav className="flex flex-col gap-1 px-3 py-2">
          {navItems.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              end={item.end}
              className={({ isActive }) =>
                cn(
                  "flex items-center gap-2.5 rounded-md px-3 py-2 text-sm font-medium transition-colors",
                  isActive
                    ? "bg-secondary text-foreground"
                    : "text-muted-foreground hover:bg-secondary/60 hover:text-foreground"
                )
              }
            >
              <item.icon className="h-4 w-4" />
              {item.label}
            </NavLink>
          ))}
        </nav>
        <div className="mt-auto px-5 py-4 border-t border-border">
          <p className="text-[11px] text-muted-foreground leading-snug">
            Every stage classification and outreach plan is generated by a
            traceable multi-agent pipeline. Nothing ships to a lead without
            explicit approval.
          </p>
        </div>
      </aside>
      <div className="flex-1 min-w-0 flex flex-col">
        <header className="md:hidden flex items-center gap-2 border-b border-border px-4 py-3 bg-surface">
          <div className="flex h-7 w-7 items-center justify-center rounded-md bg-primary text-primary-foreground">
            <Radio className="h-3.5 w-3.5" />
          </div>
          <p className="font-heading text-sm font-bold">Signalis</p>
        </header>
        <main className="flex-1 min-w-0 p-4 md:p-8 max-w-[1400px] w-full mx-auto">
          <Outlet />
        </main>
      </div>
    </div>
  )
}
